tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface-container-highest": "#e5e2e2",
                "on-secondary-fixed": "#00201a",
                "tertiary": "#000000",
                "on-tertiary-fixed": "#231a12",
                "on-tertiary-container": "#918176",
                "on-error-container": "#93000a",
                "slate-50": "#F8FAFC",
                "enterprise-blue": "#0A2540",
                "secondary-fixed-dim": "#00dfc1",
                "on-primary-fixed": "#181c22",
                "primary-fixed": "#dfe2eb",
                "on-primary-container": "#80848c",
                "inverse-surface": "#313031",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f6f3f3",
                "on-secondary": "#ffffff",
                "error": "#ba1a1a",
                "secondary-fixed": "#26fedc",
                "inverse-on-surface": "#f3f0f0",
                "tertiary-container": "#231a12",
                "on-error": "#ffffff",
                "surface-dim": "#dcd9d9",
                "tertiary-fixed": "#f3dfd2",
                "surface": "#fcf8f9",
                "surface-container": "#f0eded",
                "on-tertiary-fixed-variant": "#51443b",
                "background": "#fcf8f9",
                "surface-variant": "#e5e2e2",
                "outline-variant": "#c6c6cb",
                "on-secondary-container": "#007261",
                "outline": "#76777b",
                "tech-emerald": "#00F5D4",
                "tertiary-fixed-dim": "#d6c3b7",
                "primary-container": "#181c22",
                "surface-container-high": "#ebe7e7",
                "slate-900": "#0D1117",
                "on-primary-fixed-variant": "#43474e",
                "error-container": "#ffdad6",
                "on-background": "#1c1b1c",
                "on-tertiary": "#ffffff",
                "inverse-primary": "#c3c6cf",
                "on-surface": "#1c1b1c",
                "surface-tint": "#5b5e66",
                "primary": "#000000",
                "on-secondary-fixed-variant": "#005144",
                "on-surface-variant": "#45474b",
                "primary-fixed-dim": "#c3c6cf",
                "surface-bright": "#fcf8f9",
                "secondary": "#006b5b",
                "secondary-container": "#26fedc",
                "on-primary": "#ffffff"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "margin-mobile": "16px",
                "container-max": "1280px",
                "margin-desktop": "64px",
                "gutter": "24px",
                "unit": "4px"
            },
            "fontFamily": {
                "headline-md": ["Sora"],
                "display-lg-mobile": ["Sora"],
                "body-md": ["Inter"],
                "body-sm": ["Inter"],
                "headline-sm": ["Sora"],
                "display-lg": ["Sora"],
                "body-lg": ["Inter"],
                "label-caps": ["JetBrains Mono"]
            },
            "fontSize": {
                "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
                "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }]
            }
        },
    },
};
